name: lost
description: WhatsApp clone with flutter sdk.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  percent_indicator: ^3.0.1
  responsive_builder: ^0.4.1
  riverpod: ^0.14.0+3
  flutter_hooks: ^0.18.0
  line_icons: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^2.0.0


  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/
